name: ci-sonar

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["10.x.x"]

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Install SonarScanner
        run: |
          dotnet tool update --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run SonarScanner and tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"algowars_server" \
            /o:"algowars" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.cobertura.reportsPaths="TestResults/**/coverage.cobertura.xml"

          dotnet restore
          dotnet build \
            --no-restore
          dotnet test \
            --no-restore \
            --no-build \
            --results-directory TestResults \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/ \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletShowSummary=true

          dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: TestResults/
